# Generated by Django 4.2.1 on 2023-06-10 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"position": "Buyer"},
                related_name="team_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_lead",
            field=models.OneToOneField(
                limit_choices_to={"position": "Team Lead"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_lead",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
