# Generated by Django 4.2.1 on 2023-06-10 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_teams", "0002_alter_team_members_alter_team_team_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_creator",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
