# Generated by Django 4.2.1 on 2023-06-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("teamlead", "Team Lead"),
                    ("owner", "Owner"),
                ],
                default="buyer",
                max_length=10,
            ),
        ),
    ]
