# Generated by Django 4.2.1 on 2023-06-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_customuser_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["username"]},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                choices=[
                    ("Buyer", "Buyer"),
                    ("Team Lead", "Team Lead"),
                    ("Owner", "Owner"),
                ],
                default="Buyer",
                max_length=20,
            ),
        ),
    ]
