# Generated by Django 4.2.1 on 2023-06-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_management",
            "0003_alter_customuser_options_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_images"),
        ),
    ]
