# Generated by Django 4.2.1 on 2023-06-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0004_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="profile_images/default.jpg", upload_to="profile_images"
            ),
        ),
    ]
