# Generated by Django 4.2.1 on 2023-06-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0005_alter_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.jpg",
                null=True,
                upload_to="profile_images",
            ),
        ),
    ]
