# Generated by Django 4.2.1 on 2023-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_leads", "0002_lead_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="user",
        ),
        migrations.AddField(
            model_name="lead",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
