# Generated by Django 4.2.1 on 2023-06-18 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="created_at",
        ),
    ]
