# Generated by Django 4.2.1 on 2023-06-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                choices=[
                    ("Buyer", "Buyer"),
                    ("Team Lead", "Team Lead"),
                    ("Funds Coordinator", "Funds Coordinator"),
                    ("Owner", "Owner"),
                ],
                default="Buyer",
                max_length=20,
            ),
        ),
    ]
