# Generated by Django 4.2.1 on 2023-06-11 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_users", "0003_customuser__is_syncing_position_and_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="_is_syncing_position_and_groups",
        ),
    ]
