# Generated by Django 4.2.1 on 2023-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_users", "0004_remove_customuser__is_syncing_position_and_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                default="user_images/default.jpg",
                null=True,
                upload_to="user_images",
            ),
        ),
    ]
